- src/interfaces/bulk.js
- src/routes/bulk.js
Handle errors from bulk/readContent and bulk/doQuery
> Fix bulk read content

- package-lock.json
- package.json
- src/routes/queryUtils.js
* Accept strings 'true' and 'false' (case insensitive) as query parameters for boolean options
* Fix regular expression for checking boolean options
> Accept true false as parameters

- src/app.js
- src/config.js
- src/interfaces/bulk.js
- src/routes/bulk.js
- src/routes/prio.js
* Add recordType parameter
** settable in env RECORD_TYPE
** defaults to 'bib'
* Error using unique or merge for creates/updates if recordType is something else than 'bib'
> Add recordType parameter

- src/interfaces/logs.js
- src/interfaces/utils.js
- src/routes/queryUtils.js
Use id and correlationId as aliases to each other in queries
Error with 400 if both id and correlationId are used and they do not match
> Id and correlationId as aliases

- src/routes/prio.js
> Serve api documentation in prio

- .github/dependabot.yml
- .github/workflows/melinda-node-tests.yml
- .github/workflows/rebase-dependencies.yml
- package-lock.json
- package.json
> Update melinda rest api commons2

- package-lock.json
- package.json
- src/interfaces/bulk.js
- src/interfaces/prio.js
- src/routes/bulk.js
* Clean up logging
* 3.0.4-alpha.1
> Clean up logging (#86)

- package-lock.json
Reverts NatLibFi/melinda-rest-api-http#130
> Revert "Bump fast-xml-parser and @aws-sdk/credential-providers"

- .github/workflows/melinda-node-tests.yml
- package-lock.json
- package.json
- src/interfaces/logs.js
- src/routes/queryUtils.js
* Fix querying logs by bulkSequence
* Use updated logItemTypes, which includes inputRecordLog and resultRecordLog
* Dependency update (#152) ** Bump http-status from 1.6.2 to 1.7.0 (#151)
** Bump @babel/runtime from 7.22.11 to 7.22.15 (#150) ** Bump actions/checkout from 3 to 4 (#149)
** Bump @natlibfi/sru-client from 6.0.4 to 6.0.5 (#147)
* Update deps
* 3.2.0-alpha.2
> Add record log & Dependency update (#152) (#148)

- package-lock.json
- package.json
- src/api.json
- src/api.yaml
- src/interfaces/logs.js
* BlobSequence is a number, not a string
* 3.2.1-alpha.1
> Fix blobSequence in queueItem/logs (#155)

- .github/dependabot.yml
- .github/workflows/melinda-node-tests.yml
- package-lock.json
- package.json
* Bump @natlibfi/melinda-rest-api-commons from 4.0.13 to 4.0.15 (#163)
* Bump docker/metadata-action from 4 to 5 (#162)
* Bump docker/login-action from 2 to 3 (#161)
* Bump docker/build-push-action from 4 to 5 (#160)
* Bump uuid from 9.0.0 to 9.0.1 (#159)
* Update deps
* 3.2.2-alpha.1
> Maintenance & Dependency update

- .github/dependabot.yml
- .github/workflows/melinda-node-tests.yml
- package-lock.json
- package.json
* Dependency update (#164) ** Bump @natlibfi/melinda-rest-api-commons from 4.0.13 to 4.0.15 (#163) ** Bump docker/metadata-action from 4 to 5 (#162)
** Bump docker/login-action from 2 to 3 (#161)
** Bump docker/build-push-action from 4 to 5 (#160) ** Bump uuid from 9.0.0 to 9.0.1 (#159)
** Update deps
* 3.2.2-alpha.1
* Maintenance update (#166) ** [MRA-643], [MRA-642] Maintenance updates
** [MRA-641] Dependabot update
* 3.2.2-alpha.2
> Maintenance & Dependency update (#165)

- README.md
- package-lock.json
- package.json
- src/config.js
* MRA-716 Fix config defaults for authentication requirements (#171)
* Bump the development-dependencies group with 3 updates (#170)
** Updates `@babel/cli` from 7.22.15 to 7.23.0
** Updates `@babel/core` from 7.22.20 to 7.23.0
** Updates `eslint` from 8.49.0 to 8.50.0
* Bump the production-dependencies group with 1 update (#169)
* Update deps
* 3.2.3-alpha.2
> MRA-716 (#171) ; Dependency update (#172)

- package-lock.json
- package.json
- src/routes/logs.js
Bumps the development-dependencies group with 1 update: [eslint](https://github.com/eslint/eslint).
- [Release notes](https://github.com/eslint/eslint/releases)
- [Changelog](https://github.com/eslint/eslint/blob/main/CHANGELOG.md)
- [Commits](https://github.com/eslint/eslint/compare/v8.52.0...v8.53.0)
---
updated-dependencies:
- dependency-name: eslint dependency-type: direct:development update-type: version-update:semver-minor dependency-group: development-dependencies ...
> Fix logs/list 

- package-lock.json
- package.json
- src/routes/logs.js
* Bump the development-dependencies group with 1 update (#203)
* Remove duplicate getListOfLogs2
* Fix logs/list
* 3.3.1-alpha.1
> Fix logs/list & logs/protectLog & logs/removeLog (#204)

- package-lock.json
- package.json
- src/interfaces/bulk.js
* Simple error if queueItem did not get updated when a streamBulk job is created [MRA-739] 
* Bump the development-dependencies group with 3 updates (#208) (#210)
- Updates `@babel/core` from 7.23.2 to 7.23.3
- Updates `@babel/plugin-transform-runtime` from 7.23.2 to 7.23.3
- Updates `@babel/preset-env` from 7.23.2 to 7.23.3
* Update commons: v13.0.8-alpha.1
* 3.3.2-alpha.2
> Fix stuck on uploading [MRA-739] (#209)

- .github/workflows/melinda-node-tests.yml
- package-lock.json
- package.json
* Fix stuck on uploading [MRA-739] (#209)
* Simple error if queueItem did not get updated when a streamBulk job is created [MRA-739] 
* Bump the development-dependencies group with 3 updates (#208) (#210) Updates `@babel/core` from 7.23.2 to 7.23.3
Updates `@babel/plugin-transform-runtime` from 7.23.2 to 7.23.3 Updates `@babel/preset-env` from 7.23.2 to 7.23.3
* Bump the development-dependencies group with 6 updates (#234) | Package | From | To |
| --- | --- | --- |
| [@babel/cli](https://github.com/babel/babel/tree/HEAD/packages/babel-cli) | `7.23.0` | `7.23.4` | | [@babel/core](https://github.com/babel/babel/tree/HEAD/packages/babel-core) | `7.23.3` | `7.23.7` | | [@babel/plugin-transform-runtime](https://github.com/babel/babel/tree/HEAD/packages/babel-plugin-transform-runtime) | …
> Dependency & Maintenance update (#235)

- package-lock.json
- package.json
- src/api.json
- src/api.yaml
- src/interfaces/bulk.js
- src/routes/prio.js
- src/routes/queryUtils.js
* Add matchFailuresAsNew query parameter
* Update deps
* 3.5.0-alpha.1
> Feature handleMatchFailuresAsNew [MRA-841] (#367)

- package-lock.json
- package.json
- src/api.json
- src/api.yaml
- src/interfaces/bulk.js
- src/routes/prio.js
- src/routes/queryUtils.js
* Add matchFailuresAsNew query parameter
* NOTE: requires validator ^3.8.0 to be usable
* Update deps
* 3.5.0-alpha.1
> Feature handleMatchFailuresAsNew [MRA-841] (#367) (#368)

- package-lock.json
- package.json
- src/api.json
- src/api.yaml
- src/config.js
- src/interfaces/bulk.js
- src/routes/bulk.js
- src/routes/routeUtils.js
- Add endpoint /bulk/records for adding a chunk of maximum of 100 records to bulk
-- record input only as an application/json array of marc-record-js records
- API version 2.4
> Feature add records
